spring:
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: ${{secrets.SMTP_USERNAME}}
    password: ${{secrets.SMTP_PASSWORD}}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 15000
          starttls:
            enable: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_SERVER}:${DB_PORT:3306}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        registration:
          #Google
          google:
            client-id: ${{secrests.GOOGLE_CLIENT_ID}}
            client-secret: ${{secrets.GOOGLE_CLIENT_SECRET}}
            redirect-uri: http://localhost:8080/oauth2/callback/google
            client-name: Google
            scope:
              - email
              - profile

          naver:
            client-id: ${{secrets.NAVER_CLIENT_ID}}
            client-secret: ${{secrets.NAVER_CLIENT_ID}}
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/oauth2/callback/naver

          kakao:
            client-id: ${{secrets.KAKAO_CLIENT_ID}}
            redirect-uri: http://localhost:8080/oauth2/callback/kakao
            authorization-grant-type: authorization_code
            scope: account_email,profile_nickname
            client-name: Kakao
            client-authentication-method: client_secret_post

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id



  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect



jwt:
  issuer: ${secrets.JWT_ISSUER}
  secret_key: ${JWT_SECRET_KEY}

oauth:
  authorizedRedirectUri: http://localhost:8080/oauth2/redirect





server.port: 8080
