name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  build-and-push-image:
    env:
      IMAGE_TAG: ${{github.sha}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name : Build with Gradle
        run : ./gradlew build

      - name: Check build result
        run: |
          if [ -d build/libs ]; then
            echo "Contents of build/libs:"
              ls -al build/libs
          else
            echo "build/libs directory not found"
            exit 1
          fi

      - name: check directory and change directory
        run: ls -al && cd src/main/resources && mkdir firebase && ls-al && cd firebase
          
#      - name: create-json
#        id: create-json
#        uses: jsdaniell/create-json@v1.2.2
#        with:
#          name: "escort-8572e-firebase-adminsdk-6yrr0-c77a6887e1.json"
#          json: ${{ secrets.FCM_JSON }}

              - name: create-json
                id: create-json
                uses: jsdaniell/create-json@v1.2.2
                with:
                  name: "testJson"
                  json: ${{ secrets.FCM_JSON }}
                  dir: 'src/main/resources/firebase/'


      - name: return to root directory
        run: cd .. && cd .. && cd .. && ls -al


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: 'ggprgrkjh/kubernetes-spring-mysql-demo:${{env.IMAGE_TAG}}'
          platforms: |
            linux/arm64

      - name: Update image tag
        run: |
          sed -i 's|image: ggprgrkjh/kubernetes-spring-mysql-demo:test|image: 'ggprgrkjh/kubernetes-spring-mysql-demo:${{env.IMAGE_TAG}}'|' ./Resources/App/app-deployment.yaml
          cat ./Resources/App/app-deployment.yaml
        env:
          IMAGE_TAG: ${{github.sha}}

      - name: Check update image result
        run: |
          if [ -d ./Resources/App ]; then
            echo "Contents of ./Resources/App:"
              ls -al ./Resources/App
          else
            echo "./Resources/App directory not found"
            exit 1
          fi

      - name: change directory and delete unused FCM_SECRET
        run: ls -al && cd src/main/resources/firebase && rm -f testJson

      - name: Commit & Push change
        uses: actions-js/push@master
        with:
          github_token: ${{secrets.MY_GITHUB_TOKEN}}