name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  build-and-push-image:
    env:
      IMAGE_TAG: ${{github.sha}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name : Build with Gradle
        run : ./gradlew build


      - name: Check build result
        run: |
          if [ -d build/libs ]; then
            echo "Contents of build/libs:"
              ls -al build/libs
          else
            echo "build/libs directory not found"
            exit 1
          fi
        
        

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: 'ggprgrkjh/kubernetes-spring-mysql-demo:${{env.IMAGE_TAG}}'

      - name: Update image tag
        run: |
          sed -i 's|image: ggprgrkjh/kubernetes-spring-mysql-demo:.+|image: ggprgrkjh/kubernetes-spring-mysql-demo:${{env.IMAGE_TAG}}' ./Resources/App/app-deployment.yaml
        env:
          IMAGE_TAG: ${{ github.sha }}


      - name: Commit and Push Changes
        run: |
          git config --local user.email "ggprgrkjh@naver.com"
          git config --local user.name "junhyeongkim2"
          git add .
          git commit -m "Update image tag to ${{ env.IMAGE_TAG }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}